### ISSUE TITLE
vite build error : TypeError: hook is not a function

### ISSUE THREAD

**Issue by bluelightsky** [GreatAuk/plugin-web-update-notification#36]
rendering chunks (13)...[vite:build-html] hook is not a function
error during build:
TypeError: hook is not a function
    at applyHtmlTransforms (D:\vscodeProject\vue\vite-chatGPT\node_modules\vite\dist\node\chunks\dep-9c153816.js:21725:27)
    at Object.generateBundle (D:\vscodeProject\vue\vite-chatGPT\node_modules\vite\dist\node\chunks\dep-9c153816.js:21677:32)
    at D:\vscodeProject\vue\vite-chatGPT\node_modules\rollup\dist\shared\rollup.js:22841:40
error Command failed with exit code 1.

**Comment by bluelightsky** [comment]
my vite version is 2.8.0
